#!/bin/bash -e
######################################################################
# 
#          Custom i3bar script by Felix Brüning, 2022
#
# This program is free software: you can redistribute it and/or 
# modify it under the terms of the GNU General Public License as 
# published by the Free Software Foundation, either version 3 of 
# the License, or (at your option) any later version.
#
# This program is distributed in the hope that it will be useful, 
# but WITHOUT ANY WARRANTY; without even the implied warranty of 
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the 
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
#  along with this program. If not, see <https://www.gnu.org/licenses/>.
#
######################################################################


source break_manager

# --------------------------------------------------------------------
# Field definitions
# --------------------------------------------------------------------
break_manager_field() {
    status=$(break_manager)
    
    state_not_started="Not Started."

    if [ "$status" == "$state_not_started" ]
    then
        echo "{\"full_text\":\"BM: $status\", \"color\":\"#FFFF99\" }"
    else
        echo "{\"full_text\":\"BM: $status\", \"color\":\"#99FF99\" }"
    fi
    
}

# --------------------------------------------------------------------

# Add one json field:
# {\"full_text\":\"${<my_variable>}\" }

# --------------------------------------------------------------------
# Print i3bar command
# --------------------------------------------------------------------
# Explaination:
# ===============
#
# The 4 lines of json file has to be read from i3status.conf file, parsed
# and exported by `i3status` to json config for i3bar
# echo new JSON fields for custom data

i3status | (read line && echo "$line" && read line && echo "$line" && read line && echo "$line" && while :
do
  read line
  echo ", [$(break_manager_field), ${line#,\[}" || exit 1
done)

# --------------------------------------------------------------------
