#!/bin/bash -e
######################################################################
# 
#          Break Manager script by Felix Brüning, 2022
#
# This program is free software: you can redistribute it and/or 
# modify it under the terms of the GNU General Public License as 
# published by the Free Software Foundation, either version 3 of 
# the License, or (at your option) any later version.
#
# This program is distributed in the hope that it will be useful, 
# but WITHOUT ANY WARRANTY; without even the implied warranty of 
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the 
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
#  along with this program. If not, see <https://www.gnu.org/licenses/>.
#
######################################################################

set -e

# --------------------------------------------------------------------
# Break Manager
# --------------------------------------------------------------------

BM_45_WORK_FILE="/tmp/BM_START_45_WORK"
BM_45_FILE="/tmp/BM_START_45"
BM_50_WORK_FILE="/tmp/BM_START_50_WORK"
BM_50_FILE="/tmp/BM_START_50"

work_time_50_config=50
pause_time_50_config=10
work_time_45_config=45
pause_time_45_config=15

start_time=-1
current_time=0

# ------------------------------------
# Main Break manager 
# ------------------------------------
function break_manager_main() {
    time_file=$1
    work_file=$2
    work_time=$3
    pause_time=$4

    # ----------------------------------------
    # In state 'work-time'
    # ----------------------------------------
    if [ -f $work_file ]
    then
        # check if time file is empty
        # --> TODO invert
        if [ ! -s $time_file ]
        then
            echo $(date "+%H%M") > $time_file
        fi
        start_time=`cat $time_file`

        current_time=$(date "+%H%M")
        time_diff="$(($current_time - $start_time))"

        if [ $time_diff -eq $work_time ]
        then
            rm -rf $time_file
            touch $time_file
            rm -rf $work_file
        else
            time_left="$(($work_time - time_diff))"
            echo "$time_left minutes left to Work" 
        fi
    else
        # ----------------------------------------
        # check if time file is empty
        if [ ! -s $time_file ]
        then
            echo $(date "+%H%M") > $time_file
        fi
        start_time=`cat $time_file`

        current_time=$(date "+%H%M")
        time_diff="$(($current_time - $start_time))"

        # ----------------------------------------
        # if time diff is pause time
        # ----------------------------------------
        if [ $time_diff -eq $pause_time ]
        then
            # switch to work-mode from pause
            rm -rf $time_file
            touch $time_file
            touch $work_file
        else
            time_left="$(($pause_time - time_diff))"
            echo "$time_left minutes left for pause" 
        fi
    fi
}

# ------------------------------------
# Main Break manager wrapper
# ------------------------------------
function break_manager() {
    
    if [[ -f $BM_50_FILE || -f $BM_45_FILE ]]
    then
        if [  -f $BM_50_FILE ]
        then
            break_manager_main $BM_50_FILE $BM_50_WORK_FILE $work_time_50_config $pause_time_50_config 
        fi

        if [ -f $BM_45_FILE ]
        then
            break_manager_main $BM_45_FILE $BM_45_WORK_FILE $work_time_45_config $pause_time_45_config
        fi
        
    else
        echo "Not Started."
    fi
    
}




