#!/bin/bash
######################################################################
# 
#          Control Break Manager script by Felix Brüning
# 
# This program is free software: you can redistribute it and/or 
# modify it under the terms of the GNU General Public License as 
# published by the Free Software Foundation, either version 3 of 
# the License, or (at your option) any later version.
#
# This program is distributed in the hope that it will be useful, 
# but WITHOUT ANY WARRANTY; without even the implied warranty of 
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the 
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
#  along with this program. If not, see <https://www.gnu.org/licenses/>.
#
######################################################################


source break_manager

# ------------------------------------
# handle arguments function
# ------------------------------------
function handleArguments() {
    command=$1
    time_value=$2

    # -----------------------
    # if command is '-start'
    # -----------------------
    if [ "$command" == -start ]
    then
        if [ "$time_value" == 45 ]
        then
            echo "Starting timer 45 minutes"
            touch $BM_45_FILE
            touch $BM_45_WORK_FILE
        fi

        if [ "$time_value" == 50 ]
        then
            echo "Starting timer 50 minutes"
            touch $BM_50_FILE
            touch $BM_50_WORK_FILE
        fi
        
    fi

    # -----------------------
    # if command is '-stop'
    # -----------------------
    if [ "$command" == -stop ]
    then
        echo "Stop timer"

        if [ -f $BM_50_FILE ]
        then
            rm -rf $BM_50_FILE
        fi

        if [ -f $BM_45_FILE ]
        then
            rm -rf $BM_45_FILE
        fi
        
        if [ -f $BM_50_WORK_FILE ]
        then
            rm -rf $BM_50_WORK_FILE
        fi

        if [ -f $BM_45_WORK_FILE ]
        then
            rm -rf $BM_45_WORK_FILE
        fi
    fi
}

# ------------------------------------
# print usage
# ------------------------------------
function printUsage() {
    echo "Usage: "
    echo "-start <time>  | time: 45 or 50 [minutes]"
    echo "-stop"
}

# ------------------------------------
# Main
# ------------------------------------
if [ $# -eq 0 ]
then
    printUsage
else
    handleArguments $1 $2
fi

